FROM python:3.12-slim

WORKDIR /app

COPY requirements-validator.txt .
RUN pip install --no-cache-dir -r requirements-validator.txt

COPY validator.py .
COPY signup_shards ./signup_shards

CMD ["python", "validator.py"]