apiVersion: v1
kind: Service
metadata:
  name: spam-api
  labels:
    app: spam-api
spec:
  selector:
    app: spam-api
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP